/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ApiTest {
//    @Test void appHasAGreeting() {
//        Api classUnderTest = new Api();
//        assertNotNull(classUnderTest.(), "app should have a greeting");
//    }
}
